AfterShip/clickhouse-sql-parser

- .github/workflows/ci.yaml
- README.md
But don't have a plan to force check the coverage.
> Add the cover report to CI

- parser/ast.go
- parser/keyword.go
- parser/parse_system.go
- parser/parser_common.go
- parser/parser_table.go
- parser/testdata/ddl/grant_privilege.sql
- parser/testdata/ddl/output/grant_privilege.sql.golden.json
> Add the support of GRANT PRIVILEGE

- parser/ast.go
- parser/parser_query.go
- parser/testdata/ddl/output/bug_001.sql.golden.json
- parser/testdata/ddl/output/create_live_view_basic.sql.golden.json
- parser/testdata/ddl/output/create_materialized_view_with_empty_table_schema.sql.golden.json
- parser/testdata/ddl/output/create_view_basic.sql.golden.json
- parser/testdata/ddl/output/create_view_on_cluster_with_uuid.sql.golden.json
- parser/testdata/dml/output/insert_with_select.sql.golden.json
- parser/testdata/query/output/select_simple.sql.golden.json
- parser/testdata/query/output/select_simple_with_cte_with_column_aliases.sql.golden.json
- parser/testdata/query/output/select_simple_with_group_by_with_cube_totals.sql.golden.json
- parser/testdata/query/output/select_simple_with_is_not_null.sql.golden.json
- parser/testdata/query/output/select_simple_with_is_null.sql.golden.json
- parser/testdata/query/output/select_simple_with_top_clause.sql.golden.json
- parser/testdata/query/output/select_simple_with_with_clause.sql.golden.json
- parser/testdata/query/output/select_with_union_distinct.sql.golden.json
Hi! 
While using -format I encountered an unexpected behavior
You can see it:
SELECT * FROM clickhouse FINAL;
SELECT * FROM clickhouse LIMIT 100;
Thank you in advance!
> Added FINAL processing to SELECT and fixed conversion of selectExpr to string

- parser/parser_query.go
- parser/testdata/query/format/select_with_string_expr.sql
- parser/testdata/query/output/select_with_string_expr.sql.golden.json
- parser/testdata/query/select_with_string_expr.sql
> Allow to use STRING as the table name

- parser/ast.go
- parser/keyword.go
- parser/parser_column.go
- parser/parser_common.go
- parser/parser_query.go
- parser/testdata/query/format/select_simple_with_with_clause.sql
- parser/testdata/query/format/select_with_left_join.sql
- parser/testdata/query/output/select_simple_with_with_clause.sql.golden.json
- parser/testdata/query/output/select_with_left_join.sql.golden.json
- parser/testdata/query/select_with_left_join.sql
> Fix cannot parse LEFT JOIN correctly

- go.mod
- parser/ast.go
- parser/ast_visitor.go
- parser/visitor_test.go
resolve https://github.com/AfterShip/clickhouse-sql-parser/issues/8
> Implement visitor for AST 

- parser/ast.go
- parser/parser_view.go
- parser/testdata/ddl/create_materialized_view_basic.sql
- parser/testdata/ddl/format/create_materialized_view_basic.sql
- parser/testdata/ddl/output/bug_001.sql.golden.json
- parser/testdata/ddl/output/create_live_view_basic.sql.golden.json
- parser/testdata/ddl/output/create_materialized_view_basic.sql.golden.json
- parser/testdata/ddl/output/create_materialized_view_with_empty_table_schema.sql.golden.json
The correct syntax for create materialized view is:
```sql
CREATE MATERIALIZED VIEW [IF NOT EXISTS] [db.]table_name [ON CLUSTER] [TO[db.]name] [ENGINE = engine] [POPULATE] AS SELECT ...
```
Our original parsing implement from antlr, process was wrong, now it is fixed.
example:
```sql
CREATE
MATERIALIZED VIEW infra_bm.view_name 
ON CLUSTER 'default_cluster' TO infra_bm.table_name
(
`f1` DateTime64(3), 
`f2` String, 
`f3` String, 
`f4` String, 
`f5` String, 
`f6` Int64
) AS
SELECT f1,
f2,
visitParamExtractString(properties, 'f3')   AS f3,
visitParamExtractString(properties, 'f4')      AS f4,
visitParamExtractString(properties, 'f5')    AS f5,
visitParamExtractInt(properties, 'f6') AS f6
FROM
infra_bm.table_name1
WHERE
infra_bm.table_name1.event = 'test-event';
```
> Fix the wrong parsing of creating materialized view statements

- parser/ast.go
- parser/lexer.go
- parser/parser_column.go
- parser/parser_table.go
- parser/testdata/query/format/select_cast.sql
- parser/testdata/query/output/select_cast.sql.golden.json
- parser/testdata/query/select_cast.sql
- parser/type.go
> Fix cast expr issues

- parser/ast.go
- parser/parser_common.go
- parser/parser_query.go
- parser/parser_table.go
- parser/testdata/query/format/select_with_literal_table_name.sql
- parser/testdata/query/output/select_with_join_only.sql.golden.json
- parser/testdata/query/output/select_with_literal_table_name.sql.golden.json
- parser/testdata/query/output/select_with_string_expr.sql.golden.json
- parser/testdata/query/select_with_literal_table_name.sql
- parser/visitor_test.go
> Allow to use string as database/table name

- parser/ast.go
- parser/ast_visitor.go
- parser/parser_query.go
- parser/testdata/ddl/output/bug_001.sql.golden.json
- parser/testdata/ddl/output/create_live_view_basic.sql.golden.json
- parser/testdata/ddl/output/create_materialized_view_basic.sql.golden.json
- parser/testdata/ddl/output/create_materialized_view_with_empty_table_schema.sql.golden.json
- parser/testdata/ddl/output/create_view_basic.sql.golden.json
- parser/testdata/ddl/output/create_view_on_cluster_with_uuid.sql.golden.json
- parser/testdata/dml/output/insert_with_select.sql.golden.json
- parser/testdata/query/format/select_simple_with_with_clause.sql
- parser/testdata/query/format/select_with_join_only.sql
- parser/testdata/query/format/select_with_left_join.sql
- parser/testdata/query/format/select_with_multi_join.sql
- parser/testdata/query/output/select_simple.sql.golden.json
- parser/testdata/query/output/select_simple_with_cte_with_column_aliases.sql.golden.json
- parser/testdata/query/output/select_simple_with_group_by_with_cube_totals.sql.golden.json
- parser/testdata/query/output/select_simple_with_is_not_null.sql.golden.json
- parser/testdata/query/output/select_simple_with_is_null.sql.golden.json
- parser/testdata/query/output/select_simple_with_top_clause.sql.golden.json
- parser/testdata/query/output/select_simple_with_with_clause.sql.golden.json
- parser/testdata/query/output/select_with_join_only.sql.golden.json
- parser/testdata/query/output/select_with_left_join.sql.golden.json
- parser/testdata/query/output/select_with_literal_table_name.sql.golden.json
- parser/testdata/query/output/select_with_multi_join.sql.golden.json
- parser/testdata/query/output/select_with_string_expr.sql.golden.json
- parser/testdata/query/output/select_with_union_distinct.sql.golden.json
- parser/testdata/query/output/select_with_variable.sql.golden.json
- parser/testdata/query/select_with_multi_join.sql
> Fix cannot parse multi JOIN expressions

- parser/ast.go
- parser/parser_table.go
- parser/testdata/ddl/output/alter_table_add_column.sql.golden.json
- parser/testdata/ddl/output/alter_table_modify_column.sql.golden.json
- parser/testdata/ddl/output/alter_table_modify_column_remove.sql.golden.json
- parser/testdata/ddl/output/attach_table_basic.sql.golden.json
- parser/testdata/ddl/output/create_live_view_basic.sql.golden.json
- parser/testdata/ddl/output/create_materialized_view_basic.sql.golden.json
- parser/testdata/ddl/output/create_table_basic.sql.golden.json
- parser/testdata/ddl/output/create_table_with_keyword_partition_by.sql.golden.json
- parser/testdata/ddl/output/create_table_with_nullable.sql.golden.json
- parser/testdata/ddl/output/create_table_with_on_clsuter.sql.golden.json
- parser/testdata/ddl/output/create_table_with_sample_by.sql.golden.json
- parser/testdata/ddl/output/create_table_with_uuid.sql.golden.json
- parser/testdata/ddl/output/create_view_basic.sql.golden.json
- parser/testdata/dml/alter_table_with_comment.sql
- parser/testdata/dml/format/alter_table_with_comment.sql
- parser/testdata/dml/output/alter_table_with_comment.sql.golden.json
> Fix alter table add column cannot bring the comment field

- main.go
- parser/parser_common.go
> Fix panic while occurring the <EOF> error

- main.go
- parser/ast.go
- parser/ast_visitor.go
- parser/parse_system.go
- parser/parser_alter.go
- parser/parser_column.go
- parser/parser_common.go
- parser/parser_drop.go
- parser/parser_query.go
- parser/parser_table.go
- parser/parser_test.go
- parser/parser_view.go
- parser/testdata/ddl/output/attach_table_basic.sql.golden.json
- parser/testdata/ddl/output/create_distributed_table.sql.golden.json
- parser/testdata/ddl/output/create_materialized_view_with_empty_table_schema.sql.golden.json
- parser/testdata/ddl/output/create_table_basic.sql.golden.json
- parser/testdata/ddl/output/create_table_with_keyword_partition_by.sql.golden.json
- parser/testdata/ddl/output/create_table_with_nullable.sql.golden.json
- parser/testdata/ddl/output/create_table_with_on_clsuter.sql.golden.json
- parser/testdata/ddl/output/create_table_with_sample_by.sql.golden.json
- parser/testdata/ddl/output/create_table_with_uuid.sql.golden.json
- parser/visitor_test.go
Currently, we don't use the correct terms while parsing, all of them are called expressions. But it's not a good practice since it might cause confusing and unclear behavior.
> Unify SQL parser terms: stmt / clause / expression

- parser/parser_column.go
- parser/parser_query.go
- parser/testdata/ddl/output/bug_001.sql.golden.json
- parser/testdata/ddl/output/create_materialized_view_basic.sql.golden.json
- parser/testdata/ddl/output/create_materialized_view_with_empty_table_schema.sql.golden.json
- parser/testdata/query/format/select_table_alias_without_keyword.sql
- parser/testdata/query/output/select_cast.sql.golden.json
- parser/testdata/query/output/select_column_alias_string.sql.golden.json
- parser/testdata/query/output/select_simple.sql.golden.json
- parser/testdata/query/output/select_simple_with_bracket.sql.golden.json
- parser/testdata/query/output/select_simple_with_cte_with_column_aliases.sql.golden.json
- parser/testdata/query/output/select_simple_with_is_not_null.sql.golden.json
- parser/testdata/query/output/select_simple_with_is_null.sql.golden.json
- parser/testdata/query/output/select_table_alias_without_keyword.sql.golden.json
- parser/testdata/query/output/select_with_left_join.sql.golden.json
- parser/testdata/query/output/select_with_multi_join.sql.golden.json
- parser/testdata/query/output/select_with_string_expr.sql.golden.json
- parser/testdata/query/output/select_with_variable.sql.golden.json
- parser/testdata/query/select_table_alias_without_keyword.sql
> Fix should allow the table alias without the AS keyword

- parser/ast.go
- parser/parser_column.go
- parser/parser_common.go
- parser/parser_test.go
- parser/testdata/ddl/alter_table_add_index.sql
- parser/testdata/ddl/create_table_with_index.sql
- parser/testdata/ddl/format/alter_table_add_index.sql
- parser/testdata/ddl/format/create_table_with_index.sql
- parser/testdata/ddl/output/alter_table_add_index.sql.golden.json
- parser/testdata/ddl/output/create_table_with_index.sql.golden.json
extend the index parameters to support the float type and add parsing index tests for `ALTER TABLE ... ADD INDEX` and `CREATE TABLE ... INDEX`
index types ref: https://clickhouse.com/docs/en/optimize/skipping-indexes#skip-index-types
- minmax
- set
- bloom_filter
- tokenbf_v1
- ngrambf_v1
> Extend the index parameters to support the float type

- parser/parser_column.go
- parser/testdata/ddl/create_table_with_codec_delta.sql
- parser/testdata/ddl/format/create_table_with_codec_delta.sql
- parser/testdata/ddl/output/create_table_with_codec_delta.sql.golden.json
Issue https://github.com/AfterShip/clickhouse-sql-parser/issues/77
> Handling Delta with number literal

- parser/parser_column.go
- parser/testdata/ddl/create_table_with_codec_delta.sql
- parser/testdata/ddl/format/create_table_with_codec_delta.sql
- parser/testdata/ddl/output/create_table_with_codec_delta.sql.golden.json
https://github.com/AfterShip/clickhouse-sql-parser/issues/84
> Handling T64, DoubleDelta, Gorilla codec

- parser/ast.go
- parser/ast_visitor.go
- parser/parser_column.go
- parser/parser_table.go
- parser/testdata/query/format/select_with_query_parameter.sql
- parser/testdata/query/output/select_with_query_parameter.sql.golden.json
- parser/testdata/query/select_with_query_parameter.sql
> Add support of parsing map literal and query parameter

- parser/ast.go
- parser/parser_common.go
- parser/parser_table.go
- parser/parser_test.go
- parser/parser_view.go
- parser/testdata/ddl/create_materialized_view_basic.sql
- parser/testdata/ddl/create_table_basic.sql
- parser/testdata/ddl/format/create_materialized_view_basic.sql
- parser/testdata/ddl/format/create_table_basic.sql
- parser/testdata/ddl/output/attach_table_basic.sql.golden.json
- parser/testdata/ddl/output/bug_001.sql.golden.json
- parser/testdata/ddl/output/create_distributed_table.sql.golden.json
- parser/testdata/ddl/output/create_materialized_view_basic.sql.golden.json
- parser/testdata/ddl/output/create_materialized_view_with_empty_table_schema.sql.golden.json
- parser/testdata/ddl/output/create_table_basic.sql.golden.json
- parser/testdata/ddl/output/create_table_with_codec_delta.sql.golden.json
- parser/testdata/ddl/output/create_table_with_index.sql.golden.json
- parser/testdata/ddl/output/create_table_with_keyword_partition_by.sql.golden.json
- parser/testdata/ddl/output/create_table_with_nullable.sql.golden.json
- parser/testdata/ddl/output/create_table_with_on_clsuter.sql.golden.json
- parser/testdata/ddl/output/create_table_with_sample_by.sql.golden.json
- parser/testdata/ddl/output/create_table_with_uuid.sql.golden.json
Adding Table/View Comment Support as per document https://clickhouse.com/docs/en/sql-reference/statements/create/table
https://github.com/AfterShip/clickhouse-sql-parser/issues/105
Example:
```
CREATE TABLE IF NOT EXISTS test.events_local (
f0 String,
f1 String CODEC(ZSTD(1)),
f2 VARCHAR(255),
f3 Datetime,
f4 Datetime,
f5 Map(String,String),
f6 String,
f8 Datetime DEFAULT now(),
f9 String MATERIALIZED toString(f7['f70']),
f10 String ALIAS f11,
) ENGINE = MergeTree
PRIMARY KEY (f0, f1, f2)
PARTITION BY toYYYYMMDD(f3)
TTL f3 + INTERVAL 6 MONTH
ORDER BY (f1,f2,f3)
COMMENT 'Comment for table';
> Adding support for comment in table/view

- parser/ast.go
- parser/ast_visitor.go
- parser/parser_column.go
- parser/testdata/ddl/output/create_table_with_enum_fields.sql.golden.json
I think the column type desired a dedicated type instead of an expression.
> Minor refactor the column type interface

- parser/parser_table.go
- parser/testdata/ddl/create_table_with_null_engine.sql
- parser/testdata/ddl/format/create_table_with_null_engine.sql
- parser/testdata/ddl/output/create_table_with_null_engine.sql.golden.json
Null engine with parameters should be a valid syntax:
```antlr
engineExpr: ENGINE EQ_SINGLE? identifierOrNull (LPAREN columnExprList? RPAREN)?;
```
> Fix should allow to assign parameters for the Null engine

- parser/ast.go
- parser/ast_visitor.go
- parser/lexer.go
- parser/lexer_test.go
- parser/parse_system.go
- parser/parser_column.go
- parser/parser_common.go
- parser/parser_table.go
- parser/testdata/query/access_tuple_with_dot.sql
- parser/testdata/query/format/access_tuple_with_dot.sql
- parser/testdata/query/output/access_tuple_with_dot.sql.golden.json
> Add support of accessing the tuple with index field

- parser/ast.go
- parser/lexer.go
- parser/lexer_test.go
- parser/parse_system.go
- parser/parser_column.go
- parser/parser_common.go
- parser/parser_query.go
- parser/parser_table.go
- parser/parser_view.go
- parser/type.go
It's no need to differ the type between the operation type and token kind.
> Minor refactor the operation type to the unify token kind

- parser/ast.go
- parser/ast_visitor.go
- parser/keyword.go
- parser/lexer_test.go
- parser/parser_column.go
- parser/parser_table.go
- parser/testdata/ddl/create_table_basic.sql
- parser/testdata/ddl/format/create_table_basic.sql
- parser/testdata/ddl/output/create_table_basic.sql.golden.json
```
<column_name> JSON(max_dynamic_paths=N, max_dynamic_types=M, some.path TypeName, SKIP path.to.skip, SKIP REGEXP 'paths_regexp')
```
Only support `SKIP PATH` and `SKIP REGEXP` in this PR, other options will be supported in further PR.
> Add support of SKIP options for JSON type

- parser/ast.go
- parser/parser_column.go
- parser/testdata/ddl/create_mv_with_not_op.sql
- parser/testdata/ddl/format/create_mv_with_not_op.sql
- parser/testdata/ddl/output/create_mv_with_not_op.sql.golden.json
> Fix wrongly format the string in UnaryExpr

- parser/parser_column.go
- parser/parser_common.go
- parser/testdata/query/format/select_simple_field_alias.sql
- parser/testdata/query/output/select_simple_field_alias.sql.golden.json
- parser/testdata/query/select_simple_field_alias.sql
ClickHouse allows to not use `AS` keyword when naming selected columns:
```
SELECT col1 AS one, col2 two
FROM tbl
```
Fix it.
> Parse select item alias even without `AS` keyword

- parser/parser_column.go
- parser/testdata/query/format/select_with_keyword_in_group_by.sql
- parser/testdata/query/output/select_with_keyword_in_group_by.sql.golden.json
- parser/testdata/query/select_with_keyword_in_group_by.sql
> Fix should allow using the keyword as column name

- parser/ast.go
- parser/ast_visitor.go
- parser/parser_table.go
- parser/testdata/dml/format/insert_with_placeholder.sql
- parser/testdata/dml/insert_with_placeholder.sql
- parser/testdata/dml/output/insert_with_placeholder.sql.golden.json
The sample can refer to:
```SQL
INSERT INTO TABLE test_with_typed_columns (id, created_at) VALUES ({id:Int32}, {created_at:DateTime64(6)});
```
> Add support of the typed placeholder parameters for INSERT statement

- parser/parser_alter.go
- parser/parser_column.go
- parser/parser_common.go
- parser/parser_query.go
- parser/parser_table.go
This PR only changes the internal behavior and won't affect the parsed output.
> Refactor expectTokenKind's return value to keep consistent with expectKeyword

- parser/ast.go
- parser/parser_table.go
- parser/testdata/dml/format/insert_values.sql
- parser/testdata/dml/format/insert_with_format.sql
- parser/testdata/dml/format/insert_with_placeholder.sql
- parser/testdata/dml/format/insert_with_select.sql
- parser/testdata/dml/insert_with_format.sql
- parser/testdata/dml/output/insert_values.sql.golden.json
- parser/testdata/dml/output/insert_with_format.sql.golden.json
- parser/testdata/dml/output/insert_with_placeholder.sql.golden.json
- parser/testdata/dml/output/insert_with_select.sql.golden.json
The following syntax is valid in ClickHouse:
```SQL
INSERT INTO table_name
```
> Fix INSERT INTO should allow the empty column list

- parser/ast.go
> Fix missing the table name visitor in CREATE/ALTER table

- .github/workflows/ci.yaml
- go.mod
- parser/ast.go
- parser/testdata/ddl/create_table_with_index.sql
- parser/testdata/ddl/format/create_table_with_index.sql
- parser/testdata/ddl/output/create_table_with_index.sql.golden.json
- Fix INDEX statement parsing bug where dotted column names (e.g., `common.id`) were missing spaces in string output
- Ensure parenthesized expressions in INDEX statements don't get unwanted extra spaces
- **parser/ast.go**: Fix `TableIndex.String()` method spacing logic for column expressions
- **Test files**: Update golden test files to reflect corrected INDEX formatting
**Before:** `INDEX id_common_id_bloom_filtercommon.id TYPE bloom_filter(0.001) GRANULARITY 1`
**After:** `INDEX id_common_id_bloom_filter common.id TYPE bloom_filter(0.001) GRANULARITY 1`
> Fix INDEX column spacing bug

- parser/walk.go
- parser/walk_test.go
This started as a bug fix the `Walk` function. It skips traversing constraints if `Right` is `nil` https://github.com/AfterShip/clickhouse-sql-parser/blob/294aafbcb0009df3dad13ae5f6d4420feff6c456/parser/walk.go#L193
https://github.com/AfterShip/clickhouse-sql-parser/blob/294aafbcb0009df3dad13ae5f6d4420feff6c456/parser/walk.go#L11
This PR tries a more generic approach to prevent this bug and others by returning `true` if the node is `nil`.
I also added a test that fails without this fix
> Fix shouldn't stop on `nil` values when traversing the AST

- parser/walk.go
Thank you for this lovely module, this PR fixes a bug in the `Walk` function where it stops prematurely on `WhenClause`
> fix: Fix `Walk` logic for `When` clause

- parser/parser_column.go
- parser/parser_query.go
- parser/testdata/query/format/select_keyword_alias_no_as.sql
- parser/testdata/query/output/select_keyword_alias_no_as.sql.golden.json
- parser/testdata/query/select_keyword_alias_no_as.sql
This fix is similar to https://github.com/AfterShip/clickhouse-sql-parser/pull/148, to allow using a keyword as a column alias, as `SELECT 'Joe' name FROM users` is valid (you can check on https://sql.clickhouse.com?query=U0VMRUNUICdKb2UnIG5hbWUgRlJPTSBvdGVsLm90ZWxfbG9ncw)
> fix: Allow using keywords as alias for columns

- parser/parser_column.go
- parser/testdata/query/format/select_case_when_exists.sql
- parser/testdata/query/output/select_case_when_exists.sql.golden.json
- parser/testdata/query/select_case_when_exists.sql
This PR adds support for parsing function arguments as `SELECT` expressions. This syntax in valid in ClickHouse console
> fix: Handle select keyword inside functions
