README.md

Add coverall and github actions badge

---

parser/ast.go
parser/parser_table.go
parser/testdata/ddl/create_function_simple.sql
parser/testdata/ddl/format/create_function_simple.sql
parser/testdata/ddl/output/create_function_simple.sql.golden.json

Add the support of CREATE FUNCTION expression

---

parser/ast.go
parser/parser_query.go
parser/testdata/ddl/output/create_live_view_basic.sql.golden.json
parser/testdata/ddl/output/create_materialized_view_with_empty_table_schema.sql.golden.json
parser/testdata/ddl/output/create_view_basic.sql.golden.json
parser/testdata/ddl/output/create_view_on_cluster_with_uuid.sql.golden.json
parser/testdata/dml/output/insert_with_select.sql.golden.json
parser/testdata/query/format/select_with_union_distinct.sql
parser/testdata/query/output/select_simple.sql.golden.json
parser/testdata/query/output/select_simple_with_bracket.sql.golden.json
parser/testdata/query/output/select_simple_with_cte_with_column_aliases.sql.golden.json
parser/testdata/query/output/select_simple_with_group_by_with_cube_totals.sql.golden.json
parser/testdata/query/output/select_simple_with_is_not_null.sql.golden.json
parser/testdata/query/output/select_simple_with_is_null.sql.golden.json
parser/testdata/query/output/select_simple_with_top_clause.sql.golden.json
parser/testdata/query/output/select_simple_with_with_clause.sql.golden.json
parser/testdata/query/output/select_with_union_distinct.sql.golden.json
parser/testdata/query/select_with_union_distinct.sql

Support UNION DISTINCT with subquery

---

parser/lexer.go
parser/testdata/query/format/select_with_variable.sql
parser/testdata/query/output/select_with_variable.sql.golden.json
parser/testdata/query/select_with_variable.sql

Allow to use '$' as the start of identifier

---

parser/parser_query.go
parser/testdata/query/format/select_with_join_only.sql
parser/testdata/query/output/select_with_join_only.sql.golden.json
parser/testdata/query/select_with_join_only.sql

related context: https://github.com/AfterShip/clickhouse-sql-parser/issues/37#issuecomment-1926623733

Fix cannot parse JOIN only expression correctly

---

parser/ast.go
parser/parser_column.go
parser/parser_common.go
parser/parser_table.go
parser/testdata/query/format/select_column_alias_string.sql
parser/testdata/query/output/select_column_alias_string.sql.golden.json
parser/testdata/query/select_column_alias_string.sql

Fix cannot alias column with the literal string

---

parser/ast.go
parser/ast_visitor.go
parser/parser_alter.go
parser/testdata/ddl/alter_table_add_projection.sql
parser/testdata/ddl/format/alter_table_add_projection.sql
parser/testdata/ddl/output/alter_table_add_projection.sql.golden.json

Add support of parsing ADD PROJECTION statement

---

parser/ast.go
parser/ast_visitor.go
parser/parser_alter.go
parser/testdata/ddl/alter_table_clear_projection.sql
parser/testdata/ddl/format/alter_table_clear_projection.sql
parser/testdata/ddl/output/alter_table_clear_projection.sql.golden.json

Add support of the CLEAR PROJECTION statement

---

parser/ast.go
parser/ast_visitor.go
parser/parser_alter.go
parser/testdata/ddl/alter_table_drop_projection.sql
parser/testdata/ddl/format/alter_table_drop_projection.sql
parser/testdata/ddl/output/alter_table_drop_projection.sql.golden.json

Add support of the DROP PROJECTION statement

---

parser/lexer.go
parser/testdata/query/format/select_with_multi_line_comment.sql
parser/testdata/query/output/select_with_multi_line_comment.sql.golden.json
parser/testdata/query/select_with_multi_line_comment.sql

Fix should skip spaces before parsing the comment line

---

parser/parser_column.go
parser/testdata/query/format/select_order_by_timestamp.sql
parser/testdata/query/output/select_order_by_timestamp.sql.golden.json
parser/testdata/query/select_order_by_timestamp.sql

Fix panic while the query with order by Timestamp keyword

---

parser/ast.go
parser/parser_column.go
parser/testdata/ddl/create_table_with_enum_fields.sql
parser/testdata/ddl/format/create_table_with_enum_fields.sql
parser/testdata/ddl/output/create_table_with_enum_fields.sql.golden.json

Fix wrongly parsed the Enum type with values

---

parser/ast.go
parser/parser_column.go
parser/parser_table.go
parser/testdata/query/format/select_with_number_field.sql
parser/testdata/query/output/access_tuple_with_dot.sql.golden.json
parser/testdata/query/output/select_with_number_field.sql.golden.json
parser/testdata/query/select_with_number_field.sql

Fix column index style wasn't supported in query

---

parser/parser_table.go
parser/testdata/query/format/select_table_function_with_query.sql
parser/testdata/query/output/select_table_function_with_query.sql.golden.json
parser/testdata/query/select_table_function_with_query.sql

Add support of using the SELECT query as table function argument

---

.github/workflows/ci.yaml
parser/parser_common.go
parser/parser_query.go
parser/parser_test.go

Fix panic with the invalid SQL

---

parser/parser_table.go
parser/testdata/ddl/create_mv_with_order_by.sql
parser/testdata/ddl/format/create_mv_with_order_by.sql
parser/testdata/ddl/output/create_mv_with_order_by.sql.golden.json

Fix SubQuery was being recognized as an ident

---

parser/ast.go
parser/parser_table.go
parser/testdata/dml/create_column_with_ttl.sql
parser/testdata/dml/format/create_column_with_ttl.sql
parser/testdata/dml/output/create_column_with_ttl.sql.golden.json

Add support of TTL expression in column definition

---

parser/ast.go
parser/ast_visitor.go
parser/keyword.go
parser/parser_table.go
parser/testdata/ddl/create_table_with_ttl_policy.sql
parser/testdata/ddl/format/create_mv_with_order_by.sql
parser/testdata/ddl/format/create_table_with_ttl_policy.sql
parser/testdata/ddl/output/attach_table_basic.sql.golden.json
parser/testdata/ddl/output/create_materialized_view_with_empty_table_schema.sql.golden.json
parser/testdata/ddl/output/create_table_basic.sql.golden.json
parser/testdata/ddl/output/create_table_with_codec_delta.sql.golden.json
parser/testdata/ddl/output/create_table_with_enum_fields.sql.golden.json
parser/testdata/ddl/output/create_table_with_index.sql.golden.json
parser/testdata/ddl/output/create_table_with_keyword_partition_by.sql.golden.json
parser/testdata/ddl/output/create_table_with_nullable.sql.golden.json
parser/testdata/ddl/output/create_table_with_on_clsuter.sql.golden.json
parser/testdata/ddl/output/create_table_with_sample_by.sql.golden.json
parser/testdata/ddl/output/create_table_with_ttl_policy.sql.golden.json
parser/testdata/ddl/output/create_table_with_uuid.sql.golden.json
parser/testdata/dml/output/alter_table_with_modify_ttl.sql.golden.json
parser/testdata/dml/output/create_column_with_ttl.sql.golden.json
parser/testdata/query/output/select_order_by_timestamp.sql.golden.json
parser/testdata/query/output/select_simple_with_group_by_with_cube_totals.sql.golden.json

For the syntax, could refer to https://clickhouse.com/docs/engines/table-engines/mergetree-family/mergetree#table_engine-mergetree-ttl

Add support of parsing TTL policy when creating table

---

parser/helper.go
parser/lexer.go
parser/testdata/query/format/select_column_alias_string.sql
parser/testdata/query/output/select_column_alias_string.sql.golden.json
parser/testdata/query/select_column_alias_string.sql

Fix dollar sign should be a valid part of the identifier

---

parser/ast.go
parser/keyword.go
parser/parser_query.go
parser/testdata/ddl/output/alter_table_add_projection.sql.golden.json
parser/testdata/query/format/select_with_group_by.sql
parser/testdata/query/output/select_simple.sql.golden.json
parser/testdata/query/output/select_simple_with_group_by_with_cube_totals.sql.golden.json
parser/testdata/query/output/select_with_group_by.sql.golden.json
parser/testdata/query/output/select_with_keyword_in_group_by.sql.golden.json
parser/testdata/query/select_with_group_by.sql

Add support of `GROUPING SETS` syntax for the group by clause

---

parser/ast.go
parser/ast_visitor.go
parser/keyword.go
parser/parser_column.go
parser/parser_common.go
parser/parser_view.go
parser/testdata/ddl/create_materialized_view_with_refresh.sql
parser/testdata/ddl/format/create_materialized_view_with_refresh.sql
parser/testdata/ddl/output/bug_001.sql.golden.json
parser/testdata/ddl/output/create_materialized_view_basic.sql.golden.json
parser/testdata/ddl/output/create_materialized_view_with_empty_table_schema.sql.golden.json
parser/testdata/ddl/output/create_materialized_view_with_refresh.sql.golden.json
parser/testdata/ddl/output/create_mv_with_not_op.sql.golden.json
parser/testdata/ddl/output/create_mv_with_order_by.sql.golden.json
parser/type.go

Allow using REFRESH expression in CREATE MV syntax

---

parser/ast.go
parser/keyword.go
parser/parser_view.go
parser/testdata/ddl/create_materialized_view_with_definer.sql
parser/testdata/ddl/format/create_materialized_view_with_definer.sql
parser/testdata/ddl/format/create_materialized_view_with_empty_table_schema.sql
parser/testdata/ddl/output/bug_001.sql.golden.json
parser/testdata/ddl/output/create_materialized_view_basic.sql.golden.json
parser/testdata/ddl/output/create_materialized_view_with_definer.sql.golden.json
parser/testdata/ddl/output/create_materialized_view_with_empty_table_schema.sql.golden.json
parser/testdata/ddl/output/create_materialized_view_with_refresh.sql.golden.json
parser/testdata/ddl/output/create_mv_with_not_op.sql.golden.json
parser/testdata/ddl/output/create_mv_with_order_by.sql.golden.json

Fixes this issue https://github.com/AfterShip/clickhouse-sql-parser/issues/159

Adding support MV definer

---

parser/ast.go
parser/ast_visitor.go
parser/parser_alter.go
parser/testdata/dml/alter_table_modify_query.sql
parser/testdata/dml/format/alter_table_modify_query.sql
parser/testdata/dml/output/alter_table_modify_query.sql.golden.json

Support for https://clickhouse.com/docs/sql-reference/statements/alter/view

feat: support for ALTER TABLE MODIFY QUERY

---

parser/ast.go
parser/parser_query.go
parser/testdata/query/format/select_with_window_function.sql
parser/testdata/query/output/select_with_window_function.sql.golden.json
parser/testdata/query/select_with_window_function.sql

WINDOW clause should come after HAVING clause

fix: change WINDOW clause position
